### PR TITLE
Setting: add StorageOpt

### PR DESCRIPTION
**Pull request by AlexeyRokhin**
This fixes issue #26 and allows to configure storage options (StorageOpt).
Signed-off-by: Alexey Rokhin <arokhin@mail.ru>

### CODE REVIEW

**Comment by AlexeyRokhin** [comment]
Hi @JeanRev 
Please review it.
Tested in local virtual Windows environment (Windows docker host and Windows TeamCity)

**Comment by JeanRev** [comment]
Hi @AlexeyRokhin, that's awesome :-) I'll do some additionnal testing but the code looks all good, very well done.

**Comment by JeanRev** [comment]
Merged without further change, thanks!

**Comment by AlexeyRokhin** [comment]
Thank you @JeanRev !
What is your estimation about release date of these changes?

**Comment by JeanRev** [comment]
I try to perform a major release every 3 months or so. I'll have however a bit less time available during the next weeks, and they are two important features still incubating. So, that will be probably end of August/beginning of September.

**Pull request merged**
